/* empty css                      */import{a as f,S as p,i}from"./assets/vendor-BNsGcbod.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const m="https://pixabay.com/api/",g="50913402-008034d842f29df0686066032";async function h(r){const t={key:g,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0};return(await f.get(m,{params:t})).data}const y=document.querySelector("#search-form"),c=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".loading-message"),v=new p(".gallery a");function L(){u.classList.remove("hidden")}function b(){setTimeout(()=>{u.classList.add("hidden")},1e3)}y.addEventListener("submit",async r=>{r.preventDefault();const t=r.target.searchQuery.value.trim();if(t){r.target.searchQuery.value="",c.innerHTML="",w(),L();try{const o=await h(t);if(console.log(o.hits),l(),b(),o.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#EF4040"});return}r.target.searchQuery.value="";const a=o.hits.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item">
          <img src="${e.webformatURL}" alt="${e.tags}" />
          <div class="info">
            <div class="info-block"><span class="info-title">Likes</span><span class="info-value">${e.likes}</span></div>
            <div class="info-block"><span class="info-title">Views</span><span class="info-value">${e.views}</span></div>
            <div class="info-block"><span class="info-title">Comments</span><span class="info-value">${e.comments}</span></div>
            <div class="info-block"><span class="info-title">Downloads</span><span class="info-value">${e.downloads}</span></div>
          </div>
        </a>`).join("");c.innerHTML=a,v.refresh()}catch(o){l(),i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}}});function w(){d.classList.remove("hidden")}function l(){d.classList.add("hidden")}
//# sourceMappingURL=index.js.map
